global:
  smtp_smarthost: 'localhost:25'
  smtp_from: 'alertmanager@example.org'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'

templates:
- "/etc/alertmanager/template/*.tmpl"

route:
  repeat_interval: 1m
  receiver: infra

receivers:
- name: 'infra'
  webhook_configs:
    - url: 'http://discord:9094'