version: '3.8'

services:
  # --- Prometheus
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.24.0
    restart: unless-stopped
    ports:
      - target: 9090
        published: 9090
        protocol: tcp
        mode: host
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.retention.time=30d
      - --web.enable-lifecycle
      - --web.enable-admin-api
    volumes:
      - type: volume
        source: prometheus-volume
        target: /prometheus
      - type: bind
        source: ./prometheus
        target: /etc/prometheus
        read_only: true
    networks:
      - monitoramento-network

   # --- AlertManager
  alertmanager:
    container_name: alertmanager
    image: prom/alertmanager:v0.21.0
    restart: unless-stopped
    depends_on:
      - prometheus
    command:
      - --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - target: 9093
        published: 9093
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: alertmanager-volume
        target: /alertmanager
      - type: bind
        source: ./alertmanager
        target: /etc/alertmanager
        read_only: true
    networks:
      - monitoramento-network
  
  grafana:
    container_name: grafana
    image: grafana/grafana:6.7.5-ubuntu
    restart: unless-stopped
    depends_on:
      - prometheus
    environment:
      TZ: 'America/Recife'
      GF_SERVER_ROOT_URL: 'http://grafana.meudominio.local'
      GF_SECURITY_ADMIN_USER: 'ambiente@meudominio.local'
      GF_SECURITY_ADMIN_PASSWORD: 'Qye5tQUnsDWCIZMwJXto'
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-piechart-panel,camptocamp-prometheus-alertmanager-datasource,vonage-status-panel'
    ports:
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: grafana-volume
        target: /var/lib/grafana
    networks:
      - monitoramento-network

  # --- Discord Integration Webhook
  discord:
    container_name: discord-integration
    image: benjojo/alertmanager-discord:latest
    restart: unless-stopped
    depends_on:
      - alertmanager
    environment:
      DISCORD_WEBHOOK: 'https://discord.com/api/webhooks/799351728839327748/6bC8-n7qgTXAEje7QnfngBHfVFazVWS0kojv95LXx3yKaH67D9NlQAZDD8U4M0cV555I'
    networks:
      - monitoramento-network

  # --- Jolokia Exporter
  jolokia_exporter_testes:
    container_name: jolokia_exporter_testes
    image: scalify/jolokia_exporter:1.2.1
    restart: unless-stopped
    command: [
      "export", "/config.yml", "https://testes-unemat.esig.com.br/jolokia", "insecure"
    ]
    volumes:
      - type: bind
        source: ./jolokia_exporter/config.yml
        target: /config.yml
        read_only: true
    networks:
      - monitoramento-network

volumes:
  prometheus-volume:
    driver: local
  alertmanager-volume:
    driver: local
  grafana-volume:
    driver: local

networks:
  monitoramento-network:
    driver: bridge