global:
  scrape_interval: 15s # --- Realiza o scrape à cada 15s.
  scrape_timeout: 15s  # --- Tempo de espera máximo por uma resposta.
  evaluation_interval: 30s # --- Releitura do arquivo de regras.

# -- Configuração do AlertManager.
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# --- Path do arquivo de alertas.
rule_files:
  - "/etc/prometheus/alert.yml"

scrape_configs:
  # --- Prometheus
  - job_name: 'prometheus'
    static_configs:
    - targets: ['prometheus:9090']

  - job_name: 'alertmanager'
    static_configs:
    - targets: ['alertmanager:9093']

  - job_name: 'unemat.esig.com.br'
    static_configs:
    - targets: ['unemat.esig.com.br:9100']
      labels:
        application: 'sigufrn'
        environment: 'testes'
        hostname: 'unemat.esig.com.br'

  - job_name: 'jolokia_exporter_testes'
    scrape_interval: 30s
    static_configs:
    - targets: ['jolokia_exporter_testes:9422']
      labels:
        application: 'sigufrn'
        environment: 'testes'
        instance: 'desenv'
        hostname: 'unemat.esig.com.br'