{
 "title": "UNEMAT MTI",
 "description": "Universidade Estadual do Maranhão",
 "tags": [
  "jboss5",
  "postgres",
  "apache",
  "ufrn"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Application View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jolokia_up{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\", instance=\"srv1inst1\"}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jolokia_up{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\", instance=\"srv2inst1\"}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jolokia_up{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\", instance=\"srv3inst1\"}"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "jolokia_up{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\", instance=\"srv4inst1\"}"
    }
   ]
  },
  {
   "title": "Availability URL",
   "type": "table",
   "description": "Este painel informa o status das URLs monitoradas, informando se estão acessíveis ou não.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance, value) (probe_http_duration_seconds{costumer=\"unemat\", application=\"sigufrn\", environment=\"producao\"})"
    },
    {
     "expr": "sum by (instance, value) (probe_http_status_code{costumer=\"unemat\", application=\"sigufrn\", environment=\"producao\"})"
    }
   ]
  },
  {
   "title": "Uptime - srv1inst1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "jolokia_java_uptime{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\", instance=\"srv1inst1\"} / 1000"
    }
   ]
  },
  {
   "title": "Uptime - srv2inst1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "jolokia_java_uptime{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\", instance=\"srv2inst1\"} / 1000"
    }
   ]
  },
  {
   "title": "Uptime - srv3inst1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "jolokia_java_uptime{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\", instance=\"srv3inst1\"} / 1000"
    }
   ]
  },
  {
   "title": "Uptime - srv4inst1",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "jolokia_java_uptime{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\", instance=\"srv4inst1\"} / 1000"
    }
   ]
  },
  {
   "title": "Servers Memory Usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"} * 100) / node_memory_MemTotal_bytes{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Clock Synchronization Status",
   "type": "table",
   "description": "O node_timex_sync_status informa se o relógio local está sincronizado com um controle remoto\nrelógio. O valor é definido como zero quando a sincronização com um servidor confiável é\nperdido ou um software de sincronização de tempo está configurado incorretamente.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (hostname) (node_time_seconds - node_ntp_reference_timestamp_seconds{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"})"
    },
    {
     "expr": "sum by (hostname) (node_timex_sync_status{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"})"
    }
   ]
  },
  {
   "title": "Servers Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{customer=\"unemat\", environment=\"producao\", application=\"sigufrn\"} - node_memory_MemFree_bytes{customer=\"unemat\", environment=\"producao\", application=\"sigufrn\"} - (node_memory_Cached_bytes{customer=\"unemat\", environment=\"producao\", application=\"sigufrn\"} + node_memory_Buffers_bytes{customer=\"unemat\", environment=\"producao\", application=\"sigufrn\"})",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "JkStatus - Busy Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jk_status_balancer_member{application=\"sigufrn\", customer=\"unemat\", environment=\"producao\", type=\"busy\"}",
     "legendFormat": "{{hostname}} - {{route}}"
    }
   ]
  },
  {
   "title": "Servers System Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Last 1 minute" }
   ],
   "targets": [
    {
     "expr": "node_load1{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\", hostname=~\"app-.+.unemat.br\"}",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "node_load1{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\", hostname=~\"database-.+.unemat.br\"}",
     "legendFormat": "{{hostname}}"
    },
    {
     "expr": "node_load1{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\", hostname=~\"bal-.+.unemat.br\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Apache Connections State",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "apache_workers{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"}",
     "legendFormat": "{{hostname}} - {{state}}"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jolokia_java_memory_heap_memory_usage_used{customer=\"unemat\", environment=\"producao\", application=\"sigufrn\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Count Per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jolokia_global_request_count_request_count{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "AJP Connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jolokia_conn_unemat_inst_ajp_connection",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Request Error Count per Minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jolokia_global_request_count_error_count{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Request per Day",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jolokia_global_request_count_request_count{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"}[1d]))",
     "legendFormat": "Total Request"
    }
   ]
  },
  {
   "title": "AJP Current Threads Busy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jolokia_conn_unemat_inst_ajp_connection_busy{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data Source Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short", "label": "Connections in use" }
   ],
   "targets": [
    {
     "expr": "jolokia_ds_unemat_arquivosdb_inuseconnectioncount",
     "legendFormat": "{{instance}} - ArquivosDB"
    },
    {
     "expr": "jolokia_ds_unemat_arquivosnode1_inuseconnectioncount",
     "legendFormat": "{{instance}} - ArquivosNode1"
    },
    {
     "expr": "jolokia_ds_unemat_comumdb_inuseconnectioncount",
     "legendFormat": "{{instance}} - ComumDB"
    },
    {
     "expr": "jolokia_ds_unemat_logoperacaodb_inuseconnectioncount",
     "legendFormat": "{{instance}} - LogOperacaoDB"
    },
    {
     "expr": "jolokia_ds_unemat_sigaadb_inuseconnectioncount",
     "legendFormat": "{{instance}} - SIGAADB"
    },
    {
     "expr": "jolokia_ds_unemat_sigppdb_inuseconnectioncount",
     "legendFormat": "{{instance}} - SIGPPDB"
    },
    {
     "expr": "jolokia_ds_unemat_sigrhdb_inuseconnectioncount",
     "legendFormat": "{{instance}} - SIGRHDB"
    },
    {
     "expr": "jolokia_ds_unemat_sipacdb_inuseconnectioncount",
     "legendFormat": "{{instance}} - SIPACDB"
    }
   ]
  },
  { "title": "Operating System View", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Servers Info",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {
     "expr": "node_uname_info{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"}"
    },
    {
     "expr": "node_time_seconds{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"} - node_boot_time_seconds{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"}"
    },
    {
     "expr": "sum by (hostname) (count without(cpu, mode) (node_cpu_seconds_total{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\",mode=\"idle\"}))"
    },
    {
     "expr": "sum by (hostname) (node_memory_MemTotal_bytes{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"})"
    },
    {
     "expr": "sum by (hostname) (node_memory_SwapTotal_bytes{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"})"
    }
   ]
  },
  {
   "title": "Balancers Info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "jk_status_info{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\"}"
    }
   ]
  },
  {
   "title": "Disk Space Info",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\",fstype=~\"ext4|xfs\",mountpoint!=\"/boot\"}-0"
    },
    {
     "expr": "1-(node_filesystem_free_bytes{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\",fstype=~\"ext4|xfs\",mountpoint!=\"/boot\"} / node_filesystem_size_bytes{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\",fstype=~\"ext4|xfs\",mountpoint!=\"/boot\"})"
    },
    {
     "expr": "node_filesystem_size_bytes{customer=\"unemat\", application=\"sigufrn\", environment=\"producao\",fstype=~\"ext4|xfs\",mountpoint!=\"/boot\"}-0"
    }
   ]
  }
 ]
}